In [1]:
!pip install librosa numpy scikit-learn matplotlib soundfile audioread

  Obtaining dependency information for librosa from https://files.pythonhosted.org/packages/b5/ba/c63c5786dfee4c3417094c4b00966e61e4a63efecee22cb7b4c0387dda83/librosa-0.11.0-py3-none-any.whl.metadata
  Obtaining dependency information for soundfile from https://files.pythonhosted.org/packages/14/e9/6b761de83277f2f02ded7e7ea6f07828ec78e4b229b80e4ca55dd205b9dc/soundfile-0.13.1-py2.py3-none-win_amd64.whl.metadata
  Obtaining dependency information for audioread from https://files.pythonhosted.org/packages/7e/16/fbe8e1e185a45042f7cd3a282def5bb8d95bb69ab9e9ef6a5368aa17e426/audioread-3.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for numba>=0.51.0 from https://files.pythonhosted.org/packages/5b/82/9d425c2f20d9f0a37f7cb955945a553a00fa06a2b025856c3550227c5543/numba-0.62.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for pooch>=1.1 from https://files.pythonhosted.org/packages/a8/87/77cc11c7a9ea9fd05503def69e3d18605852cd0d4b0d3b8f15bbeb3ef1d1/pooch-1.


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# import os
# import librosa
# import numpy as np
# from sklearn.model_selection import StratifiedKFold
# from sklearn.preprocessing import StandardScaler
# from sklearn.svm import SVC
# from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# from tqdm import tqdm

# # --- 參數設定 ---
# DATASET_PATH = "C:\\Users\\周俊和\\Desktop\\資料\\GTZAN"
# genres = ['blues', 'classical', 'jazz', 'pop', 'rock']

# analysis_window = 0.025   # 25 ms
# texture_window = 1.0      # 1 秒
# overlap = 0.5             # 紋理窗重疊比例
# n_splits = 5               # K-fold 折數

# def extract_features_from_segment(y_segment, sr):
#     """對一段音訊（紋理窗）提取特徵"""
#     zcr = librosa.feature.zero_crossing_rate(y=y_segment)[0]
#     centroid = librosa.feature.spectral_centroid(y=y_segment, sr=sr)[0]
#     rolloff = librosa.feature.spectral_rolloff(y=y_segment, sr=sr)[0]
#     mfcc = librosa.feature.mfcc(y=y_segment, sr=sr, n_mfcc=13)
#     chroma = librosa.feature.chroma_stft(y=y_segment, sr=sr)

#     # 平均與變異
#     feature_vector = np.hstack([
#         np.mean(zcr), np.var(zcr),
#         np.mean(centroid), np.var(centroid),
#         np.mean(rolloff), np.var(rolloff),
#         np.mean(mfcc, axis=1), np.var(mfcc, axis=1),
#         np.mean(chroma, axis=1), np.var(chroma, axis=1)
#     ])
#     return feature_vector

# def process_audio_file(file_path):
#     """將音訊切割成多個紋理窗並提取特徵"""
#     y, sr = librosa.load(file_path, sr=None)
#     texture_samples = int(texture_window * sr)
#     hop_samples = int(texture_samples * (1 - overlap))
#     features = []

#     for start in range(0, len(y) - texture_samples, hop_samples):
#         segment = y[start:start+texture_samples]
#         features.append(extract_features_from_segment(segment, sr))
#     return np.array(features)

# # --- 主流程：提取所有特徵 ---
# all_features = []
# all_labels = []

# for genre in genres:
#     genre_path = os.path.join(DATASET_PATH, genre)
#     files = [f for f in os.listdir(genre_path) if f.endswith('.wav')]

#     for filename in tqdm(files, desc=f"Extracting {genre}"):
#         fpath = os.path.join(genre_path, filename)
#         texture_features = process_audio_file(fpath)
#         for feat in texture_features:
#             all_features.append(feat)
#             all_labels.append(genre)

# X = np.array(all_features)
# y = np.array(all_labels)

# # --- 標準化 ---
# scaler = StandardScaler()
# X = scaler.fit_transform(X)

# # --- K-fold 交叉驗證 ---
# skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# fold = 1
# acc_scores = []

# for train_index, test_index in skf.split(X, y):
#     print(f"\n=== Fold {fold} / {n_splits} ===")

#     X_train, X_test = X[train_index], X[test_index]
#     y_train, y_test = y[train_index], y[test_index]

#     model = SVC(kernel='rbf', C=10, gamma='scale')
#     model.fit(X_train, y_train)

#     y_pred = model.predict(X_test)
#     acc = accuracy_score(y_test, y_pred)
#     acc_scores.append(acc)

#     print(f"Fold {fold} accuracy: {acc:.4f}")
#     print(confusion_matrix(y_test, y_pred))
#     print(classification_report(y_test, y_pred))

#     fold += 1

# # --- 總體結果 ---
# print("\n=== Cross-validation summary ===")
# print(f"平均準確率: {np.mean(acc_scores):.4f}")
# print(f"標準差: {np.std(acc_scores):.4f}")


Extracting classical:  10%|█         | 1/10 [00:01<00:11,  1.29s/it]


KeyboardInterrupt: 

In [25]:
print(X_train.size)

82600


In [29]:
import os
import librosa
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tqdm import tqdm
import collections

# --- 參數設定 ---
DATASET_PATH = "C:\\Users\\周俊和\\Desktop\\資料\\GTZAN"
genres = ['blues', 'classical', 'jazz', 'pop', 'rock']

texture_window = 1.0
overlap = 0.5
n_splits = 5

# --- 特徵提取函數 ---
def extract_features_from_segment(y_segment, sr):
    zcr = librosa.feature.zero_crossing_rate(y=y_segment)[0]
    centroid = librosa.feature.spectral_centroid(y=y_segment, sr=sr)[0]
    rolloff = librosa.feature.spectral_rolloff(y=y_segment, sr=sr)[0]
    mfcc = librosa.feature.mfcc(y=y_segment, sr=sr, n_mfcc=13)
    chroma = librosa.feature.chroma_stft(y=y_segment, sr=sr)
    return np.hstack([
        np.mean(zcr), np.var(zcr),
        np.mean(centroid), np.var(centroid),
        np.mean(rolloff), np.var(rolloff),
        np.mean(mfcc, axis=1), np.var(mfcc, axis=1),
        np.mean(chroma, axis=1), np.var(chroma, axis=1)
    ])

def process_audio_file(file_path):
    y, sr = librosa.load(file_path, sr=None)
    texture_samples = int(texture_window * sr)
    hop_samples = int(texture_samples * (1 - overlap))
    features = []
    for start in range(0, len(y) - texture_samples, hop_samples):
        segment = y[start:start + texture_samples]
        features.append(extract_features_from_segment(segment, sr))
    return np.array(features)

# --- 計算眾數函數 ---
def most_common_label(arr):
    values, counts = np.unique(arr, return_counts=True)
    return values[np.argmax(counts)]

# --- 收集檔案路徑與標籤 ---
all_files = []
all_labels = []
genre_counts = {}
for genre in genres:
    genre_path = os.path.join(DATASET_PATH, genre)
    files = [os.path.join(genre_path, f) for f in os.listdir(genre_path) if f.endswith('.wav')]
    all_files.extend(files)
    all_labels.extend([genre]*len(files))
    genre_counts[genre] = len(files)

all_files = np.array(all_files)
all_labels = np.array(all_labels)

print("=== Dataset summary ===")
for genre, count in genre_counts.items():
    print(f"{genre}: {count} files")
print(f"Total files: {len(all_files)}\n")

# --- K-fold 交叉驗證 ---
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
fold = 1
acc_scores = []

for train_index, test_index in skf.split(all_files, all_labels):
    print(f"\n=== Fold {fold} / {n_splits} ===")
    
    # 訓練集
    train_features, train_labels = [], []
    train_slice_count = 0
    train_song_count = len(train_index)
    print(f"Train songs: {train_song_count}")
    for i in tqdm(train_index, desc="Processing training songs"):
        fpath = all_files[i]
        genre = all_labels[i]
        texture_features = process_audio_file(fpath)
        train_slice_count += len(texture_features)
        train_features.extend(texture_features)
        train_labels.extend([genre]*len(texture_features))
    print(f"Total training slices: {train_slice_count}")
    print(f"Training feature matrix shape: {np.array(train_features).shape}")
    
    # 標準化
    scaler = StandardScaler()
    X_train = scaler.fit_transform(train_features)
    y_train = np.array(train_labels)
    
    # 訓練模型
    model = SVC(kernel='rbf', C=10, gamma='scale')
    model.fit(X_train, y_train)
    
    # 測試集
    test_features_count = 0
    test_preds, test_true = [], []
    test_song_count = len(test_index)
    print(f"Test songs: {test_song_count}")
    for i in tqdm(test_index, desc="Processing test songs"):
        fpath = all_files[i]
        genre = all_labels[i]
        texture_features = process_audio_file(fpath)
        test_features_count += len(texture_features)
        texture_features = scaler.transform(texture_features)
        preds = model.predict(texture_features)
        test_preds.append(most_common_label(preds))
        test_true.append(genre)
    print(f"Total test slices: {test_features_count}")
    
    # 計算準確率
    acc = accuracy_score(test_true, test_preds)
    acc_scores.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(test_true, test_preds))
    print("Classification Report:")
    print(classification_report(test_true, test_preds))
    
    fold += 1

# --- 總體結果 ---
print("\n=== Cross-validation summary ===")
print(f"Mean Accuracy: {np.mean(acc_scores):.4f}")
print(f"Std Accuracy: {np.std(acc_scores):.4f}")


=== Dataset summary ===
blues: 10 files
classical: 10 files
jazz: 10 files
pop: 10 files
rock: 10 files
Total files: 50


=== Fold 1 / 5 ===
Train songs: 40


Processing training songs: 100%|██████████| 40/40 [00:36<00:00,  1.11it/s]


Total training slices: 2360
Training feature matrix shape: (2360, 56)
Test songs: 10


Processing test songs: 100%|██████████| 10/10 [00:09<00:00,  1.08it/s]


Total test slices: 590
Fold 1 Accuracy: 0.8000
Confusion Matrix:
[[1 0 0 0 1]
 [0 2 0 0 0]
 [0 0 1 0 1]
 [0 0 0 2 0]
 [0 0 0 0 2]]
Classification Report:
              precision    recall  f1-score   support

       blues       1.00      0.50      0.67         2
   classical       1.00      1.00      1.00         2
        jazz       1.00      0.50      0.67         2
         pop       1.00      1.00      1.00         2
        rock       0.50      1.00      0.67         2

    accuracy                           0.80        10
   macro avg       0.90      0.80      0.80        10
weighted avg       0.90      0.80      0.80        10


=== Fold 2 / 5 ===
Train songs: 40


Processing training songs: 100%|██████████| 40/40 [00:39<00:00,  1.02it/s]


Total training slices: 2360
Training feature matrix shape: (2360, 56)
Test songs: 10


Processing test songs: 100%|██████████| 10/10 [00:12<00:00,  1.28s/it]


Total test slices: 590
Fold 2 Accuracy: 1.0000
Confusion Matrix:
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
Classification Report:
              precision    recall  f1-score   support

       blues       1.00      1.00      1.00         2
   classical       1.00      1.00      1.00         2
        jazz       1.00      1.00      1.00         2
         pop       1.00      1.00      1.00         2
        rock       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10


=== Fold 3 / 5 ===
Train songs: 40


Processing training songs: 100%|██████████| 40/40 [00:47<00:00,  1.18s/it]


Total training slices: 2360
Training feature matrix shape: (2360, 56)
Test songs: 10


Processing test songs: 100%|██████████| 10/10 [00:12<00:00,  1.26s/it]


Total test slices: 590
Fold 3 Accuracy: 0.9000
Confusion Matrix:
[[1 0 0 0 1]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
Classification Report:
              precision    recall  f1-score   support

       blues       1.00      0.50      0.67         2
   classical       1.00      1.00      1.00         2
        jazz       1.00      1.00      1.00         2
         pop       1.00      1.00      1.00         2
        rock       0.67      1.00      0.80         2

    accuracy                           0.90        10
   macro avg       0.93      0.90      0.89        10
weighted avg       0.93      0.90      0.89        10


=== Fold 4 / 5 ===
Train songs: 40


Processing training songs: 100%|██████████| 40/40 [00:41<00:00,  1.03s/it]


Total training slices: 2360
Training feature matrix shape: (2360, 56)
Test songs: 10


Processing test songs: 100%|██████████| 10/10 [00:09<00:00,  1.07it/s]


Total test slices: 590
Fold 4 Accuracy: 1.0000
Confusion Matrix:
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
Classification Report:
              precision    recall  f1-score   support

       blues       1.00      1.00      1.00         2
   classical       1.00      1.00      1.00         2
        jazz       1.00      1.00      1.00         2
         pop       1.00      1.00      1.00         2
        rock       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10


=== Fold 5 / 5 ===
Train songs: 40


Processing training songs: 100%|██████████| 40/40 [00:47<00:00,  1.20s/it]


Total training slices: 2360
Training feature matrix shape: (2360, 56)
Test songs: 10


Processing test songs: 100%|██████████| 10/10 [00:12<00:00,  1.21s/it]

Total test slices: 590
Fold 5 Accuracy: 1.0000
Confusion Matrix:
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
Classification Report:
              precision    recall  f1-score   support

       blues       1.00      1.00      1.00         2
   classical       1.00      1.00      1.00         2
        jazz       1.00      1.00      1.00         2
         pop       1.00      1.00      1.00         2
        rock       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10


=== Cross-validation summary ===
Mean Accuracy: 0.9400
Std Accuracy: 0.0800
